/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaQuotes;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;

public class App {
    public static void main(String[] args) {
        try {
            Quote[] quotes = jsonParse(args[0]);
            Quote output = randomQuote(Math.random(), quotes);
            System.out.println(output);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

    }

    public static Quote[] jsonParse(String path) throws FileNotFoundException {
        Gson gson = new Gson();
        BufferedReader reader = new BufferedReader(new FileReader(path));
        Quote[] output = gson.fromJson(reader, Quote[].class);
        return output;
    }

    public static Quote randomQuote(double random, Quote[] quotes) {
        int randomIndex = (int) (random * quotes.length);
        Quote output = quotes[randomIndex];
        return output;
    }
}
