/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaQuotes;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;

public class App {
    public static void main(String[] args) {
        Quote[] output = null;
        try {
            output = jsonParse(args[0]);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

    }

    public static Quote[] jsonParse(String path) throws FileNotFoundException {
        Gson gson = new Gson();
        BufferedReader reader = new BufferedReader(new FileReader(path));
        Quote[] output = gson.fromJson(reader, Quote[].class);

        for (Quote q : output) {
            System.out.println(q.toString());
        }

        return output;
    }
}
